#ifndef _DEMO_API_TEST_H_
#define _DEMO_API_TEST_H_

#define ARG_MSGQ_NAME            "queueName"
#define ARG_MSGQ_MAXSIZE         "msgQ data size"
#define ARG_MSGQ_NUMBER          "msgQ number"
#define ARG_MSGQ_WAITINGMODE     "waiting mode"
#define ARG_MSGQ_RECV_TIMEOUT    "os timeout"
#define ARG_MSGQ_SEND_MSGID      "msgQ msg_id"
#define ARG_MSGQ_SEND_ARG1       "msgQ msg_arg1"
#define ARG_MSGQ_SEND_ARG2       "msgQ msg_arg2"
#define ARG_MSGQ_SEND_TIMEOUT    "msgQ send timeout"
#define ARG_SEMA_INITIALCOUT     "initialCount"
#define ARG_TASK_NAME            "task name"
#define ARG_TASK_STACKSIZE       "stack size"
#define ARG_TASK_PRIORITY        "stack priority"
#define ARG_TIMER_INITIALTIME    "initial time"
#define ARG_TIMER_RESCHEDULETIME "reschedule time"
#define ARG_ACCTIMER_FLAG        "accTimer flag"
#define ARG_ACCTIMER_PERIOD      "accTimer period"
#define ARG_ACCTIMER_TIMERID     "accTimer ID"

#define ARG_AUDIO_FILENAME      "audiofileName"
#define ARG_AUDIO_DIRECTPLAY    "direct"
#define ARG_AUDIO_ISSINGLE      "issingle"
#define ARG_AUDIO_ENABLE        "enable"
#define ARG_AUDIO_RECORDPATH    "recordpath"
#define ARG_AUDIO_AMR_LEN       "amrLength"
#define ARG_AUDIO_AMR_DATA      "amrData"
#define ARG_AUDIO_AMR_LEVEL     "amrLevel"
#define ARG_AUDIO_REC_OPER      "recoper"
#define ARG_AUDIO_REC_DURATION  "recduration"
#define ARG_AUDIO_PCM_DATA      "pcmData"
#define ARG_AUDIO_PCM_LEN       "pcmLen"
#define ARG_AUDIO_MP3_DATA      "mp3Data"
#define ARG_AUDIO_MP3_LEN       "mp3Len"
#define ARG_AUDIO_STARTPLAY     "startPlay"
#define ARG_AUDIO_PLAY_PATH     "playpath"
#define ARG_AUDIO_MIC_GAIN      "micgain"
#define ARG_AUDIO_VOLUME        "volume"
#define ARG_AUDIO_SAMPLE_RATE   "sampleRate"
#define ARG_AUDIO_FRAME_MODE    "framemode"

#define ARG_TTS_TEXT_TYPE       "ttsTextType"
#define ARG_TTS_TEXT_STR        "ttsText"
#define ARG_TTS_MODE            "playMode"
#define ARG_TTS_PARAM_SYSVOLUME "systemVolume"
#define ARG_TTS_PARAM_TTSVOLUME "ttsVolume"
#define ARG_TTS_PARAM_DIGITMODE "digitMode"
#define ARG_TTS_PARAM_PITCH     "pitch"
#define ARG_TTS_PARAM_SPEED     "speed"

#define ARGPOC_MODE "mode"
#define ARGPOC_SIZE "size"
#define ARG_TONEPALY_PARAM_TYPE "tonePlay type"
#define ARG_TONEPALY_PARAM_TIME "tonePlay time"
#define ARG_FREQPLAY1_PARAM_VALUE "freqplay value1"
#define ARG_FREQPLAY2_PARAM_VALUE "freqplay value2"
#define ARG_FREQPLAY_PARAM_TIME "freqplay time"
#define ARG_VOLUME_PARAM_VALUE "tone volume"
#define ARG_PCMREAD_PARAM_VALUE "pcm read length"

#define ARG_WIFISCAN_PARAM_ROUNDNUMBER  "round number"
#define ARG_WIFISCAN_PARAM_BSSIDNUMBER  "bssid number"
#define ARG_WIFISCAN_PARAM_TIMEOUT      "timeout"
#define ARG_WIFISCAN_PARAM_PRIORITY     "priority"

#ifdef FEATURE_SIMCOM_FS
#define ARG_FS_DISK             "disk"
#define ARG_FS_PATH             "filePath"
#define ARG_FS_FILEMODE         "fileMode"
#define ARG_FS_DATA             "fileData"
#define ARG_FS_DATASIZE         "dataSize"
#define ARG_FS_POSITION         "position"
#define ARG_FS_OFFSET           "offset"
#define ARG_FS_OLDNAME          "oldname"
#define ARG_FS_NEWNAME          "newname"
#define ARG_FS_SWITCHMODE       "switchMode"
#define ARG_FS_SWITCH_TO_ROOT   "C_to_Root"
#define ARG_FS_SWITCH_TO_C      "Root_to_C"
#endif

#define ARG_TCPIP_IPV4              "IPV4"
#define ARG_TCPIP_IPV6              "IPV6"
#define ARG_TCPIP_PDPID             "tcp_pdpid"
#define ARG_TCPIP_FAMILY            "tcp_family"
#define ARG_TCPIP_SOCKTYPE          "tcp_spcktype"
#define ARG_TCPIP_SOCKETFD          "tcp_socketfd"
#define ARG_TCPIP_PORT              "tcp_port"
#define ARG_TCPIP_DATASIZE          "tcp_datasize"
#define ARG_TCPIP_SERVERIP          "tcp_serverip"
#define ARG_TCPIP_SENDSIZE          "tcp_sendsize"

#define ARG_HTTPS_PARATYPE      "paraType"
#define ARG_HTTPS_PARAVALUE     "paraValue"
#define ARG_HTTPS_DATALEN       "dataLen"
#define ARG_HTTPS_METHOD        "reqMethod"
#define ARG_HTTPS_READTYPE      "readType"
#define ARG_HTTPS_READOFFSET    "readOffset"
#define ARG_HTTPS_READSIZE      "readSize"
#define ARG_HTTPS_PATHNAME      "pathName"
#define ARG_HTTPS_DIR           "Dir"

#ifdef FEATURE_SIMCOM_HTP
#define ARG_HTP_COMMAND         "htp command"
#define ARG_HTP_CMD             "htp cmd"
#define ARG_HTP_HOST_INDEX      "host_index"
#define ARG_HTP_PORT            "port"
#define ARG_HTP_VERSION         "version"
#define ARG_HTP_PROXY           "proxy"
#define ARG_HTP_PROXY_PORT      "proxy port"
#endif

#ifdef FEATURE_SIMCOM_NTP
#define ARG_NTP_COMMAND         "ntp command"
#define ARG_NTP_HOSTADDR        "host_addr"
#define ARG_NTP_TIMEZONE        "time_zone"
#endif

#define ARG_SSL_OPER            "openration"
#define ARG_SSL_ID              "client id"
#define ARG_SSL_BUF             "buffer"

#define ARG_CRYPTO_OP            "operation"
#define ARG_CRYPTO_MODE          "mode"
#define ARG_CRYPTO_CUSTOM        "custom_string"
#define ARG_CRYPTO_CUSTOM        "custom_string"
#define ARG_CRYPTO_CUSTOM_OUTLEN "out_len"
#define ARG_CRYPTO_CFG           "crypto_type"
#define ARG_CRYPTO_DATA          "crypto_data"
#define ARG_CRYPTO_PRFTYPE       "prf_type"
#define ARG_CRYPTO_SECRET        "secret"
#define ARG_CRYPTO_LABEL         "label"
#define ARG_CRYPTO_RANDOM        "random"

#ifdef FEATURE_SIMCOM_MQTT
#define ARG_MQTT_CHANNEL       "channel"
#define ARG_MQTT_INDEX         "index"
#define ARG_MQTT_SSLENABLE     "ssl_enable"
#define ARG_MQTT_CLIENTID      "client_id"
#define ARG_MQTT_ALIVE_TIME    "alive_time"
#define ARG_MQTT_SERVER_HOST     "server_host"
#define ARG_MQTT_CLEAN_SESSION   "clean session"
#define ARG_MQTT_USER_NAME       "user name"
#define ARG_MQTT_PASSWORD        "password"
#define ARG_MQTT_TOPIC_DATA      "topic"
#define ARG_MQTT_QOS             "qos"
#define ARG_MQTT_DUP             "dup"
#define ARG_MQTT_PAYLOAD_DATA    "payload data"
#define ARG_MQTT_PAYLOAD_LENGTH  "payload length"
#define ARG_MQTT_RATAINED        "retained"
#define ARG_MQTT_DISSCON_TIMEOUT "disconnect_timeout"
#define ARG_MQTT_WILLTOPIC_DATA  "willtopic data"
#define ARG_MQTT_WILLMSG_DATA    "will msg"
#define ARG_MQTT_SUBTOPIC_DATA   "subtopic data"
#define ARG_MQTT_UNSUBTOPIC_DATA "unsubtopic data"
#define ARG_MQTT_CMD_TYPE        "command type"
#define ARG_MQTT_SSL_INDEX       "ssl index"
#define ARG_MQTT_CFG_TYPE        "config type"
#define ARG_MQTT_RELATED_VALUE   "related value"
#endif

#define ARG_FTPS_PDP_ACTIVE_TYPE "pdp_active_type"
#define ARG_FTPS_HOST            "host"
#define ARG_FTPS_PORT            "port"
#define ARG_FTPS_USERNAME        "userName"
#define ARG_FTPS_PASSWORD        "passwor"
#define ARG_FTPS_SERVER_TYPE     "server_type"
#define ARG_FTPS_FILENAME        "filename"
#define ARG_FTPS_LOCATION        "location"
#define ARG_FTPS_POSITION        "position"
#define ARG_FTPS_MODE            "mode"
#define ARG_FTPS_TYPE            "type"
#define ARG_FTPS_DEMO_TEST_TIME "demo_test_time"
#define ARG_FTPS_SESSION         "session"
#define ARG_FTPS_SSLID           "ssl_id"

#define ARG_APP_MODE            "mode"
#define ARG_APP_DL_RECVTIOMEOUT "recvtimeout"
#define ARG_APP_DL_URL          "url"

#define ARG_GPIO_NUMBER "gpio number"
#define ARG_GPIO_DIRECTION "gpio direction"
#define ARG_GPIO_LEVEL "gpio level"
#define ARG_GPIO_INTERRUPT "gpio interrupt"
#define ARG_GPIO_WAKEUPENABLE "wakeup enable"
#define ARG_GPIO_PULLUPDOWN "pullupdown"
#define ARG_GPIO_CONFIG "gpio config"
#define ARG_GPIO_PINMUXFUNC "gpio pinmux func"
#define ARG_POWER_ADC_CHANNEL "adc channel"

#define ARG_UART_PORT       "uartport"
#define ARG_UART_DATALEN    "datalen"
#define ARG_UART_UARTDATA   "uartdata"
#define ARG_UART_BAUDRATE   "baudrate"
#define ARG_UART_DATABITS   "databits"
#define ARG_UART_STOPBITS   "stopbits"
#define ARG_UART_PARITYBIT  "paritybit"
#define ARG_UART_GPIONUM    "gpionum"
#define ARG_UART_DELEVEL    "delevel"
#define ARG_UART_UARTCTL    "uartctl"
#define ARG_UART_MODECTL    "modectl"

#define ARG_SLAVE_ADDR "slave addr"
#define ARG_REG_ADDR "slave reg addr"
#define ARG_REG_DATA "slave reg data"
#define ARG_DATA_LEN "slave_data_len"
#define ARG_I2C_port "I2C port"
#define ARG_I2C_clk "I2C clk"
#define ARG_SPI_port "SPI port"
#define ARG_SPI_clk "SPI clk"
#define ARG_SPI_mode "SPI work mode"
#define ARG_SPI_cs "SPI csmode"

#define ARG_SLEEP_SELECT       "sleepFlag"
#define ARG_RTC_TIME_YEAR       "year"
#define ARG_RTC_TIME_MON       "month"
#define ARG_RTC_TIME_DAY       "day"
#define ARG_RTC_TIME_HOUR       "hour"
#define ARG_RTC_TIME_MIN       "minute"
#define ARG_RTC_TIME_SEC       "second"
#define ARG_TIME_USEC          "microsecond"
#define ARG_MALLOC_SIZE        "size"

#define ARG_GNSS_POWER         "gnss power"
#define ARG_GNSS_MODE          "gnss mode"
#define ARG_GNSS_NMEA_OUT      "gnss nmea out"
#define ARG_GNSS_NMEA_PORT     "gnss nmea port"
#define ARG_GNSS_START_MODE    "gnss start mode"
#define ARG_GNSS_BAUD_RATE     "gnss baud rate"
#define ARG_GNSS_NMEA_RATE     "gnss nmea rate"
#define ARG_GNSS_NMEASENTENCE  "gnss nmea sentence"
#define ARG_GNSS_GPS_INFO_GET  "gnss gps info time"
#define ARG_GNSS_CMD           "gnss cmd"

#endif  /*_DEMO_API_TEST_H_*/

